# Generated by Django 4.1 on 2023-09-11 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(help_text='User ID', primary_key=True, serialize=False)),
                ('login_id', models.CharField(max_length=32, unique=True, verbose_name='user 아이디')),
                ('login_pw', models.CharField(max_length=128, verbose_name='user 비밀번호')),
            ],
        ),
        migrations.CreateModel(
            name='User_consultant',
            fields=[
                ('id', models.BigAutoField(help_text='User ID', primary_key=True, serialize=False)),
                ('login_id', models.CharField(max_length=32, unique=True, verbose_name='상담사 아이디')),
                ('login_pw', models.CharField(max_length=128, verbose_name='상담사 비밀번호')),
            ],
        ),
        migrations.CreateModel(
            name='User_Medical',
            fields=[
                ('id', models.BigAutoField(help_text='User ID', primary_key=True, serialize=False)),
                ('login_id', models.CharField(max_length=32, unique=True, verbose_name='의료진 아이디')),
                ('login_pw', models.CharField(max_length=128, verbose_name='의료진 비밀번호')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(help_text='Result ID', primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('measurement_classification', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=10)),
                ('counseling_classification', models.CharField(max_length=10)),
                ('normal_value', models.CharField(max_length=10)),
                ('user', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_user', to='dtx.user')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(help_text='Plan ID', primary_key=True, serialize=False)),
                ('classification', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('detail', models.CharField(max_length=10)),
                ('goal', models.CharField(max_length=10)),
                ('plan', models.CharField(max_length=10)),
                ('evaluation', models.CharField(max_length=10)),
                ('user', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_user', to='dtx.user')),
            ],
        ),
        migrations.CreateModel(
            name='Counseling',
            fields=[
                ('id', models.BigAutoField(help_text='Counseling ID', primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('classification', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('user', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counseling_user', to='dtx.user')),
            ],
        ),
    ]
